spring:
  application:
    name: urbankicks
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=newsd61;encrypt=true;trustServerCertificate=true
    username: sa
    password: 28102003
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jackson:
    property-naming-strategy: SNAKE_CASE
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:uploads/
  jpa:
    hibernate:
    ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

server:
  port: 8080

api:
  prefix: /api/v1

file:
  upload-dir: uploads